#!/bin/bash
# Genrador de headers

gdk-pixbuf-csource --raw --name=icon_en_linea icon.png > icon_imagen.h
gdk-pixbuf-csource --raw --name=detener_en_linea detener.png > detener_imagen.h
gdk-pixbuf-csource --raw --name=icon_en_linea icon.png > icon_imagen.h
gdk-pixbuf-csource --raw --name=pantalla_completa_en_linea pantalla_completa.png > pantalla_completa_imagen.h
gdk-pixbuf-csource --raw --name=pausar_en_linea pausar.png > pausar_imagen.h
gdk-pixbuf-csource --raw --name=reproducir_en_linea reproducir.png > reproducir_imagen.h
gdk-pixbuf-csource --raw --name=usb_conectado_en_linea usb_conectado.png > usb_conectado_imagen.h
gdk-pixbuf-csource --raw --name=usb_desconectado_en_linea usb_desconectado.png > usb_desconectado_imagen.h

gdk-pixbuf-csource --raw --name=senial_00_en_linea senial_00.png > senial_00_imagen.h
gdk-pixbuf-csource --raw --name=senial_01_en_linea senial_01.png > senial_01_imagen.h
gdk-pixbuf-csource --raw --name=senial_02_en_linea senial_02.png > senial_02_imagen.h
gdk-pixbuf-csource --raw --name=senial_03_en_linea senial_03.png > senial_03_imagen.h
gdk-pixbuf-csource --raw --name=senial_04_en_linea senial_04.png > senial_04_imagen.h
gdk-pixbuf-csource --raw --name=senial_05_en_linea senial_05.png > senial_05_imagen.h
gdk-pixbuf-csource --raw --name=senial_06_en_linea senial_06.png > senial_06_imagen.h
gdk-pixbuf-csource --raw --name=senial_07_en_linea senial_07.png > senial_07_imagen.h
gdk-pixbuf-csource --raw --name=senial_08_en_linea senial_08.png > senial_08_imagen.h
gdk-pixbuf-csource --raw --name=senial_09_en_linea senial_09.png > senial_09_imagen.h
gdk-pixbuf-csource --raw --name=senial_10_en_linea senial_10.png > senial_10_imagen.h

