#!/bin/bash
# My first script

echo "Añadiendo sotfware necesario...\n"							#Mostrar mensaje
apt-get install g++ libusb-1.0-0-dev libgtk-3-dev

echo "Añadiendo repositorios...\n"									#Mostrar mensaje
sudo add-apt-repository ppa:videolan/stable-daily
apt-get update
apt-get install vlc libvlc-dev

shopt -s xpg_echo
echo "Para la instalación TDA LINUX debe ser super usuario."	#Mostrar mensaje

mkdir -p /opt/TDA_LINUX  							#Crea la carpeta TDA_LINUX

echo "Compilando...\n"									#Mostrar mensaje
g++ main.cpp -std=c++11 -lusb-1.0 -lvlc -pthread -rdynamic -lX11 -s `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0` -o tda_executable -w #Compilae el código fuente y crea el ejecutable

mv tda_executable /opt/TDA_LINUX 			#mueve el ejecutable a la carpeta TDA_LINUX 
cp logo.png /opt/TDA_LINUX 					#mueve el ejecutable a la carpeta TDA_LINUX 

echo "Creando acceso directo...\n"					#Mostrar mensaje
touch /opt/TDA_LINUX/TDA.desktop 					#crea el archivo del lanzador en la carpeta TDA_LINUX llamado TDA
shopt -s xpg_echo
echo "[Desktop Entry]\nVersion=0.1\nName=TDA_LINUX\nComment=Televisión Digitla Abierta Venezolana\nExec=/opt/TDA_LINUX/tda_executable\nIcon=/opt/TDA_LINUX/logo.png\nTerminal=false\nType=Application\nCategories=Utility;Application;" > /opt/TDA_LINUX/TDA.desktop

chmod 755 /opt/TDA_LINUX/TDA.desktop 				#Hacer el launcher ejecutable

echo "Copindo regla udev...\n"					#Mostrar mensaje
cp -R 40_usb.rules /etc/udev/rules.d/ 			#Mover las reglas udev al sistema

sudo udevstart									#Comenzar las reglas
sudo /etc/init.d/udev restart

